spring:
    config:
        name: query
    datasource:
        driver-class-name: org.postgresql.Driver
        username: xxxxxxxxx
        password: xxxxxxxxx
        url: jdbc:postgresql://localhost:5432/xxxxxxxxx
        hibernate:
            ddl-auto: none
            event.merge.entry_copy_observer: allow
        hikari:
            auto-commit: true
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
            maximum-pool-size: 20
            minimum-idle: 5
    jpa:
        database: POSTGRESQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.enable_lazy_load_no_trans: true
lamis:
    temp-dir: runtime/
    module-path: modules

lamisplus:
    datasource:
        module:
            driver-class-name: org.postgresql.Driver
            username: postgres
            password: smilez
            url: jdbc:postgresql://localhost:5432/lamisplus_x
            hikari:
                    auto-commit: true
                    data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true
                    maximum-pool-size: 5
                    minimum-idle: 3
    base-url:
        version-one: "/api/v1/"
    secugen:
        biometrics:
            server-url: http://localhost:8282
            server-port: 8282
            timeout: 3000
            quality: 80
server:
    port: 9090
